version: 0.0
Resources:
  - myFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: myFunction
        Alias: live
        CurrentVersion: "1"  # Replaced placeholder
        TargetVersion: "2"   # Replaced placeholder
Hooks:
  BeforeAllowTraffic:
    - location: scripts/pre_validation.sh
      timeout: 300
      runas: root
  AfterAllowTraffic:
    - location: scripts/post_validation.sh
      timeout: 300
      runas: root
