version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - cd lambda/myFunction
      - npm install
  build:
    commands:
      - echo Building the application...
      - zip -r function.zip .
      - aws lambda publish-version --function-name myFunction --description "New version from CodeBuild" --query 'Version' --output text > ../version.txt
artifacts:
  files:
    - lambda/myFunction/function.zip
    - version.txt
